package com.test.images.exception.handler;

public enum ErrorCodes {

	REQUEST_INVALID, INTERNAL_SERVER_ERROR, REQUEST_UNAUTHORIZED, SYSTEM_UNAVAILABLE, PARTIAL_REQUEST,
	PROTOCOL_SWICHING, MOVED_PERMANENTLY, MOVED_TEMPORARILY, RESOUNCE_NOT_MODIFIED, NOT_FOUND, MANDATORY_HEADER_MISSING

}
